### ISSUE TITLE
TODOs and Roadmap

### ISSUE THREAD

**Issue by Jytesh** [keyvhq/keyv#1]
So what should we start doing, I upgraded the deps and did nothing else in the packages I have touched need to update keyv-redis to the new test suite and start publishing

**Comment by Jytesh** [comment]
Need to enable coveralls and travis ci on all repos to get CI and coverages

**Comment by Kikobeats** [comment]
can I suggest GitHub Actions instead of Travis? 

Travis changed their pricing for OSS making it a less attractive product

**Comment by Jytesh** [comment]
Sure just need to update the workflow files, I am not sure how coveralls works but it should integrate with Github Actions as well I assume?

**Comment by Jytesh** [comment]
Also someone took the name keyvhq on npm so need to make an org there too

**Comment by Jytesh** [comment]
keyvjs is already in use as well

**Comment by Kikobeats** [comment]
@Jytesh I reserved it 🙂

**Comment by Kikobeats** [comment]
I own `keyvhq` namespace on npm; let me add you for publishing packages

**Comment by Jytesh** [comment]
I think [this issue](https://github.com/lukechilds/keyv/issues/36) and [this one](https://github.com/lukechilds/keyv/issues/25) are the major ones, typings/monorepo are also mostly done in [casey webb's fork](https://github.com/caseywebb/keyv/tree/monorepo+typescript)

**Comment by Jytesh** [comment]
I am more inclined towards adding typings and [testing those ](https://github.com/avajs/ava/blob/main/docs/recipes/typescript.md#for-packages-without-type-module) instead of a full typescript translation ( as I don't know ts ) but I'll leave that to you

[Related PR adding typings](https://github.com/lukechilds/keyv/pull/30)

**Comment by Jytesh** [comment]
Absolutely, its the typescript translation that I'm reluctant about, updating each repo is too cumbersome

**Comment by Jytesh** [comment]
Should I name the adapter packages as @keyvhq/keyv-* or just @keyvhq/*

**Comment by Jytesh** [comment]
Also https://github.com/keyvhq/monorepo is up :)

**Comment by Jytesh** [comment]
Will merge into this repo once its done

**Comment by Jytesh** [comment]
Github Actions are enabled :D

**Comment by Jytesh** [comment]
Snyk & Coveralls require owner access to add, so you must add those, what's next?

**Comment by Kikobeats** [comment]
I'm trying to enable coveralls but I'm not seeing the organization on the coveralls dashboard.

Maybe for GH just you need to use the GitHub integration? https://github.com/marketplace/actions/coveralls-github-action

It think you can skip Snyk

**Comment by Jytesh** [comment]
Alright I'll add that action, you need to give coveralls OAuth access and then grant it permissions as a Github App in your GitHub settings to see the org in the coveralls dash

**Comment by Jytesh** [comment]
The actions *should* automatically create it so I will look into that

**Comment by Kikobeats** [comment]
<img width="741" alt="Screen Shot 2021-04-18 at 18 38 54" src="https://user-images.githubusercontent.com/2096101/115153282-602b4b80-a075-11eb-93d5-4f8c986ecb9d.png">

all right, approved!

**Comment by Jytesh** [comment]
We need separate coverage stats for each package right?

**Comment by Jytesh** [comment]
Coveralls would average it if we sent it all as in one repo

**Comment by Jytesh** [comment]
and would you mind adding me as owner to keyvhq as well

**Comment by Kikobeats** [comment]
added as owner 🎉

**Comment by Kikobeats** [comment]
here a tip for setup coverage in a monorepo:

1. in the "root" repo, add a script for executing all the tests: https://github.com/microlinkhq/metascraper/blob/master/package.json#L119

2. when an individual package test is run, it creates the coverage file at the root repo: https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper/package.json#L78

3. when all tests finished, just merge all the partial coverage as one: https://github.com/microlinkhq/metascraper/blob/master/package.json#L111

**Comment by Jytesh** [comment]
aight

**Comment by Jytesh** [comment]
Thoughts on deprecating url based connections for 'official storage adapters' and just include them as a store?

**Comment by Kikobeats** [comment]
IMHO this is creating unnecessary code dependency:

```js
const keyv = new Keyv('mysql://user:pass@localhost:3306/dbname');
```

better if the library use memory by default and make it configurable via `store` option:

```js
const keyv = new Keyv();
const keyv = new Keyv({ store : new KeyvMySQL('mysql://user:pass@localhost:3306/dbname' }));
```

**Comment by Jytesh** [comment]
Yeah exactly

**Comment by Jytesh** [comment]
[![Coverage Status](https://coveralls.io/repos/github/keyvhq/keyv/badge.svg?branch=master)](https://coveralls.io/github/keyvhq/keyv?branch=master) yey

**Comment by Kikobeats** [comment]
All the pending PR merged 👏
