### ISSUE TITLE
[Suggestion] Change NPM information

### ISSUE THREAD

**Issue by VoIcanis** [keyvhq/keyv#11]
If you are unable to gain access to publish this at the @keyv entry on NPM, you should change all documentation to point away from lukechilds to this fork https://www.npmjs.com/package/@keyvhq/keyv. Such as:

npm install --save ~~keyv~~ @keyvhq/keyv
npm install --save ~~@keyv~~ @keyvhq/redis
npm install --save ~~@keyv~~ @keyvhq/mongo
npm install --save ~~@keyv~~ @keyvhq/sqlite
npm install --save ~~@keyv~~ @keyvhq/postgres
npm install --save ~~@keyv~~ @keyvhq/mysql

Along with areas like:
![image](https://user-images.githubusercontent.com/673642/122625733-a2bcd480-d074-11eb-9641-7670f222e928.png)

**Comment by Jytesh** [comment]
Will do, haven't gotten to documentation yet :)
