### ISSUE TITLE
Expose asyncIterable, keys(), values() and entries()

### ISSUE THREAD

**Issue by Jytesh** [keyvhq/keyv#5]
Need to do this for all storage adapters

- [x] Mongo
- [x] Redis
- [x] PostgreSQL
- [x] MySQL
- [x] SQLite

**Comment by Kikobeats** [comment]
why this? iterate a large collection will be performed very bad 🤔

**Comment by Jytesh** [comment]
Its probably the most requested feature for keyv, we can maybe expose this and not put it into keyv directly and let the end user get it if needed from store?

**Comment by Jytesh** [comment]
redis has scan, mongo has cursor, its the sql libs that dont expose some kind of chunked iteration

**Comment by Jytesh** [comment]
Is my [implementation](https://github.com/keyvhq/keyv/commit/a93d602f73c8a9efadd979ecb7652f99c74abb83.diff) alright?

**Comment by Jytesh** [comment]
the iterator can be consumed with a for await loop, and extensions can use the iterator to get keys(), values() and entries(), which should be storage adaptor independent

**Comment by Jytesh** [comment]
Added key iterator, should add for values and entries as well? and maybe add some tests for those

**Comment by Jytesh** [comment]
Tests needed to get coverage back to acceptable levels

**Comment by Kikobeats** [comment]
Thanks for all the effort 🙏
